struct ModelMod cameras[] = {
	{"Browse Directory", "dir","directory"},
	{"Agfa ePhoto 307", "photopc", "olympus"},
 	{"Agfa ePhoto 780", "photopc", "olympus"}, 
 	{"Agfa ePhoto 1280", "photopc", "olympus"}, 
 	{"Agfa ePhoto 1680", "photopc", "olympus"}, 
 	{"Apple QuickTake 200", "photopc", "olympus"}, 
 	{"Apple QuickTake 150", "photopc", "olympus"}, 
 	{"Canon PowerShot 350", "photopc", "olympus"}, 
 	{"Chinon ES-1000", "photopc", "olympus"}, 
 	{"Epson PhotoPC 500", "photopc", "olympus"}, 
 	{"Epson PhotoPC 550", "photopc", "olympus"}, 
 	{"Epson PhotoPC 600", "photopc", "olympus"}, 
 	{"Epson PhotoPC 700", "photopc", "olympus"}, 
	{"Fuji DS-7", "fuji","fuji"},
 	{"Hewlett Packard C20", "konica_qm100","konica_qm100"}, 
 	{"Hewlett Packard C30", "konica_qm100", "konica_qm100"},
	{"Kodak DC20", "kodak_dc2x", "kodak_dc2x"}, 
	{"Kodak DC25", "kodak_dc2x", "kodak_dc2x"}, 
 	{"Konica QM100", "konica_qm100", "konica_qm100"},
 	{"Minolta Dimmage", "photopc", "olympus"}, 
 	{"Nikon CoolPix 100", "photopc", "olympus"}, 
 	{"Nikon CoolPix 300", "photopc", "olympus"}, 
 	{"Nikon CoolPix 600", "photopc", "olympus"}, 
 	{"Nikon CoolPix 900", "photopc", "olympus"}, 
 	{"Nikon CoolPix 900S", "photopc", "olympus"}, 
 	{"Olympus D-220L", "photopc", "olympus"}, 
 	{"Olympus D-300L", "photopc", "olympus"}, 
 	{"Olympus D-320L", "photopc", "olympus"}, 
 	{"Olympus D-340L", "photopc", "olympus"}, 
 	{"Olympus D-500L", "photopc", "olympus"}, 
 	{"Olympus D-600L", "photopc", "olympus"}, 
 	{"Olympus C-400L", "photopc", "olympus"}, 
 	{"Olympus C-410L", "photopc", "olympus"}, 
 	{"Olympus C-800L", "photopc", "olympus"}, 
 	{"Olympus C-820L", "photopc", "olympus"}, 
 	{"Olympus C-900L Zoom", "photopc", "olympus"}, 
 	{"Olympus C-1000L", "photopc", "olympus"}, 
 	{"Olympus C-1400L", "photopc", "olympus"}, 
 	{"Panasonic Coolshot KXl-600A", "photopc", "olympus"}, 
	{"Philips ESP80", "philips","philips"}, 
	{"Ricoh RDC-300", "ricoh_300z", "ricoh_300z"},
	{"Ricoh RDC-300Z", "ricoh_300z", "ricoh_300z"},
	{"Ricoh RDC-4200", "philips","philips"}, 
	{"Ricoh RDC-4300", "philips","philips"}, 
 	{"Sanyo VPC-G210", "photopc", "olympus"}, 
 	{"Sanyo VPC-G250", "photopc", "olympus"}, 
 	{"Sony DSC-F1", "photopc", "olympus"}, 
	{"", NULL}
};

