/* Automatically generated by po2tbl.sed from GnoCam.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Do you really want to delete the %i selected files?", 2},
  {"Do you really want to delete the selected file?", 3},
  {"Could not delete file!", 4},
  {"No files selected!", 5},
  {"Please select a camera first!", 6},
  {"Could not find ", 7},
  {"Could not load image!", 8},
  {"Could not get preview from the camera!", 9},
  {"Could not get the file list from the camera!", 10},
  {"Could not set camera properties!", 11},
  {"Could not fine ", 12},
  {"Could not get camera properties!", 13},
  {"Please select only one camera.", 14},
  {"Please select one camera first.", 15},
  {"Could not get camera abilities!", 16},
  {"You have to indicate a name!", 17},
  {"Name of camera cannot be empty string!", 18},
  {"You have to indicate a port!", 19},
  {"Could not get number of ports!", 20},
  {"Could not get port information!", 21},
  {"Could not find port!", 22},
  {"You have to indicate a model!", 23},
  {"Could not set camera model!", 24},
  {"Could not get folder list!", 25},
  {"Could not get model name!", 26},
  {"Could not get number of supported models!", 27},
  {"Could not get port info!", 28},
  {"The configuration file is corrupt!", 29},
  {"It seems that you are running\n", 30},
  {"Could not get file from camera!", 31},
};

int _msg_tbl_length = 31;
