#ifndef __GNOCAM_IDL__
#define __GNOCAM_IDL__

#include <Bonobo.idl>

module GNOME {

	interface Camera : Bonobo::Unknown {
		/* The Camera can be accessed through BonoboStorage */

		exception NotSupported {};
		exception IOError {};

		enum ErrorCode {
			ERROR
		};
		
		/*
		 * Returns either an ErrorCode or a CORBA_string defining
		 * the path to the new image.
		 */
		oneway void captureImage (
				in Bonobo::Listener listener);
	};

	interface GnoCam : Bonobo::Unknown {

		typedef sequence<string> ModelList;
		typedef sequence<string> PortList;

		exception NotFound {};
	
		ModelList getModelList ();
		PortList  getPortList  ();

		enum ErrorCode {
			ERROR
		};

		/*
		 * Those functions either return a GNOME_Camera or an
		 * ErrorCode.
		 */
		oneway void getCamera (in Bonobo::Listener listener);
		oneway void getCameraByModel (
				in Bonobo::Listener listener,
				in string model);
		oneway void getCameraByModelAndPort (
				in Bonobo::Listener listener,
				in string model, in string port);
	};
};

#endif /* __GNOCAM_IDL__ */
