#include <Bonobo.idl>

module GNOME {

	exception Cancelled {};

	interface Camera : Bonobo::Unknown {
		/* The Camera can be accessed through BonoboStorage and
		   BonoboControl, latter will give you access to the
		   configuration options. */

		exception NotSupported {};
		exception IOError {};

		Bonobo::Stream capturePreview ();
		
		/* The path to the new image will be returned. */
		string captureImage ()
			raises (Cancelled, NotSupported, IOError);
	};

	interface GnoCam : Bonobo::Unknown {

		exception NotFound {};
	
		Camera getCamera ()
			raises (NotFound, Cancelled);
		Camera getCameraByName (in string name)
			raises (NotFound);
	};
};

