#ifndef GPHOTO_IDL
#define GPHOTO_IDL

#include <Bonobo.idl>

module GNOME {
module Gphoto {

	enum DebugLevel {
		DEBUG_LEVEL_NONE,
		DEBUG_LEVEL_LOW,
		DEBUG_LEVEL_MEDIUM,
		DEBUG_LEVEL_HIGH
	};

	interface Backend : Bonobo::Unknown {
	
		exception GenericError {};
		
		void init (in DebugLevel level)
			raises (GenericError);
	};

};
};

#endif 
