#!/bin/bash

# This script should be called as "ciabot %{}" from loginfo.
# Sample loginfo line:
# ALL $CVSROOT/CVSROOT/ciabot %{}
# Put that in your CVSROOT/loginfo, then set the variables at the top of this
# script.  Then commit this file to your CVSROOT, and add it to
# CVSROOT/checkoutlist, and
#   echo | mail -s "JoinChannel #myproject" commits@picogui.org

projectname="gphoto"  # will announce to channel #<whatever you put here>
returnaddress="asl@launay.org"

# You should turn stripnewlines on if you tend to write short blocks
# of text, and off if you tend to have any formatting.  If you stick
# full changelog entries in your commit messages, definitely turn it
# off.
stripnewlines=false
#stripnewlines=true

# If your logs don't include the name of the modified file, and you want to
# show it, turn this on
includefilename=false
#includefilename=true

# Deliver directly to the bot:
commitaddress="commits@picogui.org"
# Sourceforge projects might need to deliver via users.sf.net (slower)
#commitaddress="cia@users.sf.net"

#################### End of what you'll generally need to change

echo -n "Notifying #${projectname}..."

maxlines=6
message=`cat`
uname=`id -un`
branch=`echo "$message" | grep "^[ 	]*Tag:" | awk -F: ' { print $2 } ' | sed 's/ //g'`
lineno=`echo "$message" | grep -n "Log Message:" | awk -F: ' { print $1 } '`
message=`echo "$message" | sed "1,${lineno}d"`
newline=`echo`

if [ "$message" != "`echo \"$message\" | head -n $maxlines`" ]; then
# The following line appears to be the only way to insert a newline at
# that place.
    message="`echo \"$message\" | head -n $(($maxlines - 1))`
<...>"
fi

if $stripnewlines; then
    message=`echo -n "$message" | tr '\n\r' ' '`
fi

module=`echo $1 | cut -d/ -f1`

if test -n "$branch"; then
	branch=" ({green}$branch{normal})"
fi

if $includefilename; then
	directory=`echo $1 | cut -d" " -f1`
	filename=`echo $1 | cut -d" " -f2 | cut -d"," -f1`
	module="$directory/$filename"
fi

tmpfile="/tmp/$uname-$projectname"
cat <<EOF >$tmpfile
From: $returnaddress
To: $commitaddress
Content-Type: text/plain;
Subject: Announce $projectname

commit by {yellow}$uname{normal} to {green}$module{normal}$branch: $message
EOF

if [ -e /tmp/lastlog-$uname-$projectname ]; then
    if ! diff /tmp/lastlog-$uname-$projectname $tmpfile &>/dev/null; then
        # there are differences, so this is a different commit
        cat $tmpfile | /usr/sbin/sendmail -t
        mv $tmpfile /tmp/lastlog-$uname-$projectname
    else
        # it's just cvs spamming us from another directory
        rm $tmpfile
    fi
else
    cat $tmpfile | /usr/sbin/sendmail -t
    mv $tmpfile /tmp/lastlog-$uname-$projectname
fi

echo "done."
