#!/bin/bash
# Check for common errors in source files and disallow commit if one is detected

repository="$1"
shift

while [ "$1" != "" ]
do
	file="$1"
	echo "Checking file: $file"
	cat "$file"
	shift
done

exit 0
