.\" Man Page for gPhoto by scott... :)
.\" groff -man -Tascii foo.1
.\"
.TH GPHOTO 1 "NOVEMBER 1999" GNU "User Manuals"
.SH NAME
gPhoto \- GNU Project Digital Camera Program
.SH SYNOPSIS
.B gphoto [-h] [-n] [-s # 
.I filename 
.B ] 
.B [-t # 
.I filename 
.B ]
.B [-p 
.I filename
.B ]
.br
.B gphoto [-d #] [-l 
.I filename
.B ]
.SH DESCRIPTION
.B gPhoto
is an universal, free GTK+ application that will allow
downloading, saving, and manipulation of images from several
different digital still camera models.

gPhoto has a basic command line interface, which is handy,
if you want to set up a web camera, and use gphoto in a 
script, e.g. with Perl/PHP.

.SH USAGE
.IP gphoto <option> <# of picture> <filename>
.SH OPTIONS
.TP
.I "\-n"
display the # of pictures
.TP
.I "\-s # filename"
save image # as filename
.TP
.I "\-t # filename"
save thumbnail # as filename
.TP
.I "\-p filename"
take picture and save as filename
.TP
.I "\-d #"
delete image # from camera
.TP
.I "\-l filename"
save live preview as filename
.TP
.I "\-h"
display help screen
.SH FILES
.I $HOME/.gphoto/gphotorc
.RS
gPhoto configuration file
.SH BUGS
http://bugs.gnome.org/db/pa/lgphoto.html
.SH UPDATES
http://www.gphoto.org/download.php3
.SH AUTHORS
.B 
Scott Fritzinger <scottf@unr.edu>
.br
Eugene Crosser <crosser@average.org
.br
Matt Martin <matt.martin@ieee.org>
.br
Werner Almesberger <almesber@lrc.di.epfl.ch>
.br
Ole W. Saastad <o.w.saastad@kjemi.uio.no>
.br
Anne Bezemer <costar@panic.et.tudelft.nl>
.br
Gus Hartmann <hartmann@cs.wisc.edu>
.br
Gary Ross <gdr@hooked.net>
.br
Phill Hugo <phill@gphoto.org>
.br
Ed Legowski <edlegowski@pobox.com>
.br
Toshiki Fujisawa <gphoto@fujisaw.gr.jp>
.br
M. Adam Kendall <joker@penguinpub.com>
.br
Mark Davies <mdavies@dial.pipex.com>
.br
Michael McCormack <mccormac@aals27.alcatel.com.au>
.br
Pedro Caria <pmiguel@maquina.com>
.br
Del Simmons <del@gphoto.org>
.br
Bob Paauwe <bpaauwe@bobsplace.com>
.br
Cliff Wright <cliff@snipe444.org>
.br
Beat Christen <spiff@longstreet.ch>
.br
Warren Baird <wjbaird@bigfoot.com>
.br
Brent D. Metz <bmetz@vt.edu>
.br
Brian Hirt <bhirt@loopy.berkhirt.com>
.br
Randy D. Scott <scottr@wwa.com>
.br
David Brownell <david-b@pacbell.net>
.br
Paul S. Jenner <psj@mustec.eu.org>
.br
Henning Zabel <henning@uni-paderborn.de>
.br
Rasmus Andersen <rasmus@diku.dk>
.br
Tuomas Kuosmanen <tigert@gimp.org>
.br
Ole Kristian Aamot <ole@gnu.org>
.SH "SEE ALSO"
.BR gdk,
.BR gtk+,
.BR imlib
