#!/bin/sh

base="$(dirname "$0")"
date="$(env TZ=UTC date -I)"
sshost="$(cat .sshost)"
cd "$base" || exit 1

echo "Running upload..."
rsync -avz dist-files/*.tar.bz2 "${sshost}:n-dimensional.de/snapshots/${date}/bz2/"
rsync -avz .htfixupload "${sshost}:n-dimensional.de/snapshots/${date}/"
echo "Fixing stuff..."
ssh "${sshost} "n-dimensional.de/snapshots/${date}/.htfixupload"
echo "Done."
