#define __DYNLIBTEST_LIB__
#include <dynlibtest.h>

char *me(MODULE, lib_data) = "<MODULE>" MODULE_STRING "</MODULE>";

FUNC_BODY(MODULE,0)
FUNC_BODY(MODULE,1)
FUNC_BODY(MODULE,2)
FUNC_BODY(MODULE,3)
FUNC_BODY(MODULE,4)
